call PR_DROP_TABLE ('ACT_ID_INFO', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_ID_GROUP', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_ID_MEMBERSHIP', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_ID_USER', 'ACTIVITI');