call PR_DROP_INDEX ('ACT_IDX_HI_PRO_INST_END', 'ACTIVITI');
call PR_DROP_INDEX ('ACT_IDX_HI_PRO_I_BUSKEY', 'ACTIVITI');
call PR_DROP_INDEX ('ACT_IDX_HI_ACT_INST_START', 'ACTIVITI');
call PR_DROP_INDEX ('ACT_IDX_HI_ACT_INST_END', 'ACTIVITI');
call PR_DROP_INDEX ('ACT_IDX_HI_DETAIL_PROC_INST', 'ACTIVITI');
call PR_DROP_INDEX ('ACT_IDX_HI_DETAIL_ACT_INST', 'ACTIVITI');
call PR_DROP_INDEX ('ACT_IDX_HI_DETAIL_TIME', 'ACTIVITI');
call PR_DROP_INDEX ('ACT_IDX_HI_DETAIL_NAME', 'ACTIVITI');

call PR_DROP_TABLE ('ACT_HI_PROCINST', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_HI_ACTINST', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_HI_TASKINST', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_HI_DETAIL', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_HI_COMMENT', 'ACTIVITI');
call PR_DROP_TABLE ('ACT_HI_ATTACHMENT', 'ACTIVITI');
